// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9l3vVk2xSncHcnsNMKWhdCiWD2mZOmPo',
    appId: '1:312913709110:web:bb03502ca4f81401223097',
    messagingSenderId: '312913709110',
    projectId: 'chat-app-bd25c',
    authDomain: 'chat-app-bd25c.firebaseapp.com',
    databaseURL: 'https://chat-app-bd25c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-bd25c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALOJKD5cCYxlYu7FkqcbKD50p_b19-7Rs',
    appId: '1:312913709110:android:24c4e72c8e93af3c223097',
    messagingSenderId: '312913709110',
    projectId: 'chat-app-bd25c',
    databaseURL: 'https://chat-app-bd25c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-bd25c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIXwzUbyRH5cCO7DwD_rug3WBobxhzCCQ',
    appId: '1:312913709110:ios:ea5d02ffda2208f9223097',
    messagingSenderId: '312913709110',
    projectId: 'chat-app-bd25c',
    databaseURL: 'https://chat-app-bd25c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-bd25c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIXwzUbyRH5cCO7DwD_rug3WBobxhzCCQ',
    appId: '1:312913709110:ios:ea5d02ffda2208f9223097',
    messagingSenderId: '312913709110',
    projectId: 'chat-app-bd25c',
    databaseURL: 'https://chat-app-bd25c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-bd25c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9l3vVk2xSncHcnsNMKWhdCiWD2mZOmPo',
    appId: '1:312913709110:web:3c4ece6f1f63a8a7223097',
    messagingSenderId: '312913709110',
    projectId: 'chat-app-bd25c',
    authDomain: 'chat-app-bd25c.firebaseapp.com',
    databaseURL: 'https://chat-app-bd25c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-bd25c.appspot.com',
  );

}